### ISSUE TITLE
Log-Spam

### ISSUE THREAD

**Issue by zapalotta** [PureStorage-OpenConnect/pso-explorer#21]
Is there an option to stop PSOX from logging every single HTTP request? The logs gets filled with 
127.0.0.1 -  02/Aug/2021:05:07:23 +0000 "POST /index.php" 200
127.0.0.1 -  02/Aug/2021:05:07:23 +0000 "GET /index.php" 200
127.0.0.1 -  02/Aug/2021:05:07:25 +0000 "POST /index.php" 200
127.0.0.1 -  02/Aug/2021:05:07:25 +0000 "POST /index.php" 200
127.0.0.1 -  02/Aug/2021:05:07:25 +0000 "POST /index.php" 200
127.0.0.1 -  02/Aug/2021:05:07:27 +0000 "POST /index.php" 200
127.0.0.1 -  02/Aug/2021:05:07:29 +0000 "POST /index.php" 200
127.0.0.1 -  02/Aug/2021:05:07:31 +0000 "POST /index.php" 200
127.0.0.1 -  02/Aug/2021:05:07:32 +0000 "GET /index.php" 200
127.0.0.1 -  02/Aug/2021:05:07:32 +0000 "GET /index.php" 200
127.0.0.1 -  02/Aug/2021:05:07:33 +0000 "POST /index.php" 200
127.0.0.1 -  02/Aug/2021:05:07:35 +0000 "POST /index.php" 200

Running on OCP 3.11.

Debug is of
        - name: APP_DEBUG
          value: "false"

PSOX Version: v0.5.10

Best,
Dirk

**Comment by rdeenik** [comment]
Hi Dirk,

This was caused by php-fpm being quite chatty indeed. I've just pushed an update (https://github.com/PureStorage-OpenConnect/pso-explorer-container/releases/tag/v0.5.11) which disables this verbose logging of php-fpm. Regular NGINX logging and actual application logging has not changed.

Regard,
Remko
